Hero buttons responsive bug fixed and repo-card also
max-programming/hacktoberfest-projects pull request #217
Opened 2024-10-01 18:54 UTC by SharizHussain

Your **recent button issue** fixed 
and previous **responsive issue** also solved 

please label me approved and merge after check it

2024-10-01 19:33 UTC, max-programming commented on package-lock.json
Can you please delete the lockfile or put it in `.gitignore`?
This repo uses pnpm

2024-10-01 19:34 UTC, max-programming requested changes

2024-10-01 19:34 UTC, max-programming commented on src/env.mjs
I don't think there is a need for this
If it throws an error, you can just remove this env variable from `.env.local` if it is empty

2024-10-01 19:34 UTC, max-programming commented on package-lock.json
Can you put the lockfile in gitignore, this project uses pnpm so I don't want to have conflicts with npm

2024-10-01 19:36 UTC, max-programming commented
Looks good but why do the buttons stick together?

![image](https://github.com/user-attachments/assets/0983dcb1-5eb3-4e19-a3fd-52f7cdf669d0)

2024-10-01 19:42 UTC, SharizHussain commented
I now fixed those in latest push

On Wed, 2 Oct 2024, 01:06 Usman S. (Max Programming), <
***@***.***> wrote:

> Looks good but why do the buttons stick together?
>
> image.png (view on web)
> <https://github.com/user-attachments/assets/0983dcb1-5eb3-4e19-a3fd-52f7cdf669d0>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/max-programming/hacktoberfest-projects/pull/217#issuecomment-2386837948>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFFALHVKUGWKMH37LANWUQ3ZZL2UXAVCNFSM6AAAAABPGGKLOOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOBWHAZTOOJUHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-01 20:02 UTC, max-programming commented
That looks good! Thanks

2024-10-01 20:28 UTC, SharizHussain commented
Sure now I have added the package-lock.json file in gitignore and navbar's sign in button was sticky to hacktoberfest is fixed.


![WhatsApp Image 2024-10-02 at 01 35 51](https://github.com/user-attachments/assets/17634207-4f84-4cf0-9884-516f0af9a092)


![Screenshot from 2024-10-02 01-32-39](https://github.com/user-attachments/assets/d58d7472-8c17-4ece-abf6-5aacb7c1d2f7)

2024-10-02 05:06 UTC, max-programming approved these changes

2024-10-02 05:06 UTC, merged

2024-10-02 05:07 UTC, max-programming commented
@all-contributors add @SharizHussain for bug, code

2024-10-02 05:23 UTC, SharizHussain commented
If any bug or UI related feature you can tell me later

Thanks 👍

On Wed, 2 Oct 2024, 10:38 allcontributors[bot], ***@***.***>
wrote:

> @max-programming <https://github.com/max-programming>
>
> I've put up a pull request
> <https://github.com/max-programming/hacktoberfest-projects/pull/219> to
> add @SharizHussain <https://github.com/SharizHussain>! 🎉
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/max-programming/hacktoberfest-projects/pull/217#issuecomment-2387636264>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFFALHQP2SV577F3XCVE233ZZN5T7AVCNFSM6AAAAABPGGKLOOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOBXGYZTMMRWGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>